### ISSUE TITLE
[Bug] 发送图片无响应

### ISSUE THREAD

**Issue by lancer-wang** [nonebot/adapter-red#16]
vps上安装的Chronocat  最新版

我使用
img = Message(MessageSegment.image(img_path))
然后bot.send(img)
发送一直无响应
这个img我打印出来大概是 [image: {'file': '地址.jpg'}]

**Comment by lancer-wang** [comment]
文字可以正常发送

**Comment by RF-Tar-Railt** [comment]
img_path是什么

**Comment by RF-Tar-Railt** [comment]
image(file: Union[Path, BytesIO, bytes])

**Comment by lancer-wang** [comment]
> img_path是什么

就是我图片的地址
我是从gocq过来迁移的。。。

**Comment by RF-Tar-Railt** [comment]
> > img_path是什么
> 
> 就是我图片的地址 我是从gocq过来迁移的。。。

那么你需要使用pathlib.Path 包装一层

```python
from pathlib import Path

MessageSegment.image(Path(img_path))
```

奇怪，你没有开类型检查吗（

**Comment by lancer-wang** [comment]
> > > img_path是什么
> > 
> > 
> > 就是我图片的地址 我是从gocq过来迁移的。。。
> 
> 那么你需要使用pathlib.Path 包装一层
> 
> ```python
> from pathlib import Path
> 
> MessageSegment.image(Path(img_path))
> ```
> 
> 奇怪，你没有开类型检查吗（

刚才改用send-anything 那边也是这样说的 。。。
确实没开检查，我本地没代码，我改的在线的
