### ISSUE TITLE
[Bug] 未能自动检测 Chronocat 配置

### ISSUE THREAD

**Issue by qianxuu** [nonebot/adapter-red#17]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://chronocat.vercel.app) 并仍然认为这是一个Bug

# Bug

## 问题

服务器为 debian 12，使用 `pip install nonebot-adapter-red[auto_detect]` 安装了 red 适配器，docker 运行 Chronocat，并将配置文件映射到了家目录，但是 red 无法自动读取到 Chronocat 配置

## 使用环境:
- 操作系统 (Windows/Linux/Mac): Linux
- Python 版本: Python 3.11.2
- Nonebot2 版本: 2.1.0
- Chronocat 版本: [0.0.52](https://hub.docker.com/layers/chronoc/at/0.0.52/images/sha256-6c7decc54216bfc5bf66ec5a474f5dc54064ecd2f309a9b30240b0b8b55d2014?context=explore)
- 是否使用 `BetterQQNT`: 未对 docker 容器进行任何修改，应该未使用

## 日志/截图

```
10-11 11:55:16 [DEBUG] nonebot | Loaded adapters: RedProtocol                                                                                                                         
10-11 11:55:16 [ERROR] nonebot | Error when running startup function. Ignored!                                                                                                        
Traceback (most recent call last):                                                                                                                                                    
  File "<string>", line 15, in <module>                                                                                                                                               
  File "/root/nb2/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 331, in run                                                                                           
    get_driver().run(*args, **kwargs)                                                                                                                                                 
  File "/root/nb2/.venv/lib/python3.11/site-packages/nonebot/drivers/none.py", line 70, in run                                                                                        
    loop.run_until_complete(self._serve())                                                                                                                                            
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete                                                                                                  
    self.run_forever()                                                                                                                                                                
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever                                                                                                         
    self._run_once()                                                                                                                                                                  
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once                                                                                                          
    handle._run()                                                                                                                                                                     
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run                                                                                                                      
    self._context.run(self._callback, *self._args)                                                                                                                                    
  File "/root/nb2/.venv/lib/python3.11/site-packages/nonebot/drivers/none.py", line 74, in _serve                                                                                     
    await self._startup()                                                                                                                                                             
> File "/root/nb2/.venv/lib/python3.11/site-packages/nonebot/drivers/none.py", line 82, in _startup                                                                                   
    await self._lifespan.startup()                                                                                                                                                    
  File "/root/nb2/.venv/lib/python3.11/site-packages/nonebot/drivers/_lifespan.py", line 36, in startup                                                                               
    await self._run_lifespan_func(self._startup_funcs)                                                                                                                                
  File "/root/nb2/.venv/lib/python3.11/site-packages/nonebot/drivers/_lifespan.py", line 30, in _run_lifespan_func                                                                    
    await cast(ASYNC_LIFESPAN_FUNC, func)()                                                
  File "/root/nb2/.venv/lib/python3.11/site-packages/nonebot/adapters/red/adapter.py", line 67, in startup
    raise RuntimeError(
RuntimeError: No bots found in config! 
Please check your config file and make sure it's correct.
10-11 11:55:16 [INFO] nonebot | Application startup completed.
```

直接 cat `~/.chronocat/config/chronocat.yml` 文件能读取到

![image](https://github.com/nonebot/adapter-red/assets/62287903/798931e5-971d-4d5f-b96e-595e07465121)

**Comment by RF-Tar-Railt** [comment]
命令行输入这个看看

```
python3 -c "import pathlib;print(pathlib.Path('~/.chronocat/config/chronocat.yml').expanduser().exists())"
```

**Comment by RF-Tar-Railt** [comment]
以及发一下chronocat.yml的内容

**Comment by qianxuu** [comment]
> 命令行输入这个看看
> 
> ```
> python3 -c "import pathlib;print(pathlib.Path('~/.chronocat/config/chronocat.yml').expanduser().exists())"
> ```

(nb2) root@debian:~/nb2# python3 -c "import pathlib;print(pathlib.Path('~/.chronocat/config/chronocat.yml').expanduser().exists())"
True

**Comment by qianxuu** [comment]
> 以及发一下chronocat.yml的内容

也是自动生成的，未修改过，已脱敏
```
# yaml-language-server: $schema=https://chronocat.vercel.app/config-v0.schema.json
#
################################################################
#                      Chronocat 配置文件
################################################################
#
# 你好！
#
# 这是 Chronocat 的配置文件。Chronocat 的所有配置以及每个账号
# 的独立配置都存放在这个文件里。
#
# 这是 Chronocat 配置的文档：
# https://chronocat.vercel.app/config
# 如果还没有看过的话，请先看一下！
#
# 如果你现在并不是使用完整功能的编辑器编辑此文件的话，
# 我们推荐你使用一款完整功能的编辑器来编辑！
# 这样的编辑器在你不小心改错配置的时候会智能地给出提示。
# 想要了解更多请查看上面的文档 ↑
#
################################################################
#                           全局配置
################################################################
#
# 下面的配置是通用的！如果你只登录一个账号，
# 那么只需修改下面这部分配置即可！
#
################################################################

# servers：服务配置
#
# 配置 Chronocat 开启的服务。需要尤其注意服务列表的格式哦~
servers:
  # type：服务类型
  #
  # 开启 red 服务只需要指定 type 为 red 即可。
  - type: red

    # token：服务密码
    #
    # Chronocat 已经自动生成了随机密码。要妥善保存哦！
    # 客户端使用服务时需要提供这个密码！
    token: 'xxx'

    # port：服务端口
    #
    # Chronocat 开启 red 服务的端口，默认为 16530。
    port: 16530

  # 开启 satori 服务与上面相同，指定 type 为 satori 即可。
  - type: satori

    # 这里的 token 与上面的相同，
    # 但你也可以进行更换，让每个服务使用不同的服务密码。
    token: 'xxx'

    # satori 服务的默认端口为 5500。
    port: 5500
#
################################################################
#                           账号配置
################################################################
overrides:
  ##############################################################
  #
  # 下面的配置是每个账号专属的！修改下面的配置会覆盖上面的配置哦~
  # 修改的时候要特别注意：账号前空两格，账号内配置要空四格哦！
  #
  ##############################################################

  10000:
    servers:
      - type: red
        token: 'xxx'
        port: 16531
      - type: satori
        token: 'xxx'
        port: 5501

```

**Comment by RF-Tar-Railt** [comment]
怪事了
看看你的.env

**Comment by qianxuu** [comment]
> 怪事了 看看你的.env

.env
```
ENVIRONMENT=dev
DRIVER=~httpx+~websockets
DRIVER=~aiohttp
```

.env.dev
```
LOG_LEVEL=DEBUG
SUPERUSERS=["xxx"]
NICKNAME=["xxx"]
COMMAND_START=["/", ""]
COMMAND_SEP=[".", " "]
HOST=0.0.0.0
web_host=127.0.0.1
cos_cd=0
```

**Comment by RF-Tar-Railt** [comment]
> > 怪事了 看看你的.env
> 
> .env
> ```
> ENVIRONMENT=dev
> DRIVER=~httpx+~websockets
> DRIVER=~aiohttp
> ```
> 
> .env.dev
> ```
> LOG_LEVEL=DEBUG
> SUPERUSERS=["xxx"]
> NICKNAME=["xxx"]
> COMMAND_START=["/", ""]
> COMMAND_SEP=[".", " "]
> HOST=0.0.0.0
> web_host=127.0.0.1
> cos_cd=0
> ```

请仔细阅读readme

如果需要自动检测你需要填写配置项
RED_AUTO_DETECT=true

**Comment by qianxuu** [comment]
> > > 怪事了 看看你的.env
> > 
> > 
> > .env
> > ```
> > ENVIRONMENT=dev
> > DRIVER=~httpx+~websockets
> > DRIVER=~aiohttp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > .env.dev
> > ```
> > LOG_LEVEL=DEBUG
> > SUPERUSERS=["xxx"]
> > NICKNAME=["xxx"]
> > COMMAND_START=["/", ""]
> > COMMAND_SEP=[".", " "]
> > HOST=0.0.0.0
> > web_host=127.0.0.1
> > cos_cd=0
> > ```
> 
> 请仔细阅读readme
> 
> 如果需要自动检测你需要填写配置项 RED_AUTO_DETECT=true

啊这，原来那个标题是配置名，没理解过来。。。加上后好了，谢啦

**Comment by RaTaiHok** [comment]
> > > 怪事了 看看你的.env
> > 
> > 
> > .env
> > ```
> > ENVIRONMENT=dev
> > DRIVER=~httpx+~websockets
> > DRIVER=~aiohttp
> > ```
> > 
> > 
> > .env.dev
> > ```
> > LOG_LEVEL=DEBUG
> > SUPERUSERS=["xxx"]
> > NICKNAME=["xxx"]
> > COMMAND_START=["/", ""]
> > COMMAND_SEP=[".", " "]
> > HOST=0.0.0.0
> > web_host=127.0.0.1
> > cos_cd=0
> > ```
> 
> 请仔细阅读readme
> 
> 如果需要自动检测你需要填写配置项 RED_AUTO_DETECT=true
自动检测开启后显示的这个，但是pyyaml一直都是有的:
10-15 03:53:00 [SUCCESS] nonebot | NoneBot is initializing...
10-15 03:53:00 [INFO] nonebot | Current Env: dev
10-15 03:53:00 [DEBUG] nonebot | Loaded Config: {'driver': '~httpx+~websockets+~aiohttp', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'red_auto_detect': True, 'environment': 'dev'}
10-15 03:53:01 [INFO] nonebot | RedProtocol | Auto detect chronocat config...
10-15 03:53:01 [ERROR] nonebot | RedProtocol | Please install `PyYAML` to enable auto detect!
10-15 03:53:01 [DEBUG] nonebot | Succeeded to load adapter "RedProtocol"
10-15 03:53:01 [SUCCESS] nonebot | Succeeded to load plugin "single_session" from "nonebot.plugins.single_session"
10-15 03:53:01 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
10-15 03:53:01 [SUCCESS] nonebot | Running NoneBot...
10-15 03:53:01 [DEBUG] nonebot | Loaded adapters: RedProtocol
10-15 03:53:01 [WARNING] nonebot | RedProtocol | No bots found in config!
Please check your config file and make sure it's correct.
10-15 03:53:01 [INFO] nonebot | Application startup completed.

在尝试无果后选择手动，结果如下:
![a921b58dcb4404d4c711fbe0d580f980_720](https://github.com/nonebot/adapter-red/assets/99812350/8d558fec-ea2d-4e2f-926b-6fc4c39cf77e)

**Comment by RaTaiHok** [comment]
> > > > 怪事了 看看你的.env
> > > 
> > > 
> > > .env
> > > ```
> > > ENVIRONMENT=dev
> > > DRIVER=~httpx+~websockets
> > > DRIVER=~aiohttp
> > > ```
> > > 
> > > 
> > > .env.dev
> > > ```
> > > LOG_LEVEL=DEBUG
> > > SUPERUSERS=["xxx"]
> > > NICKNAME=["xxx"]
> > > COMMAND_START=["/", ""]
> > > COMMAND_SEP=[".", " "]
> > > HOST=0.0.0.0
> > > web_host=127.0.0.1
> > > cos_cd=0
> > > ```
> > 
> > 
> > 请仔细阅读readme
> > 如果需要自动检测你需要填写配置项 RED_AUTO_DETECT=true
> 
> 自动检测开启后显示的这个，但是pyyaml一直都是有的: 10-15 03:53:00 [SUCCESS] nonebot | NoneBot is initializing... 10-15 03:53:00 [INFO] nonebot | Current Env: dev 10-15 03:53:00 [DEBUG] nonebot | Loaded Config: {'driver': '~httpx+~websockets+~aiohttp', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'red_auto_detect': True, 'environment': 'dev'} 10-15 03:53:01 [INFO] nonebot | RedProtocol | Auto detect chronocat config... 10-15 03:53:01 [ERROR] nonebot | RedProtocol | Please install `PyYAML` to enable auto detect! 10-15 03:53:01 [DEBUG] nonebot | Succeeded to load adapter "RedProtocol" 10-15 03:53:01 [SUCCESS] nonebot | Succeeded to load plugin "single_session" from "nonebot.plugins.single_session" 10-15 03:53:01 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo" 10-15 03:53:01 [SUCCESS] nonebot | Running NoneBot... 10-15 03:53:01 [DEBUG] nonebot | Loaded adapters: RedProtocol 10-15 03:53:01 [WARNING] nonebot | RedProtocol | No bots found in config! Please check your config file and make sure it's correct. 10-15 03:53:01 [INFO] nonebot | Application startup completed.
> 
> 在尝试无果后选择手动，结果如下: ![5d2b8602e096ce20e44ab4b625998a2d](https://user-images.githubusercontent.com/99812350/275285638-e8a2f7c1-dc0f-4062-83e4-7cee884ab991.jpg)

又进行了一次尝试，新建了一个没有虚拟环境的项目，登上了
建议在readme里加一个说明
