### ISSUE TITLE
[Bug]: 发送群文件会导致ntqq本体崩溃

### ISSUE THREAD

**Issue by AnHelios** [nonebot/adapter-red#19]
### 确认项

- [X] 问题的标题明确
- [X] 我翻阅过其他的 issue 并且找不到类似的问题
- [X] 我已经阅读了[相关文档](https://chronocat.vercel.app) 并仍然认为这是一个 Bug
- [X] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Windows

### Python 版本

3.11.4

### NoneBot 版本

 2.1.1

### 适配器

0.5.1

### 协议端

0.0.49

### 描述问题

1.版本：
QQNT: 9.9.0.14619（64 位）windows
LiteLoaderQQNT: 0.5.3
框架: nonebot
协议适配器: adapter-red

2.问题:
使用bot.send_group_message(group_id, MessageSegment.file(Path(file_path)))向qq群发送文件会直接导致QQNT本体崩溃

### 复现步骤

使用bot.send_group_message(group_id, MessageSegment.file(Path(file_path)))向qq群发送文件会直接导致QQNT本体崩溃

**Comment by RF-Tar-Railt** [comment]
我寻思你不是在chronocat那边提了issue了吗
