### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by FrostN0v0** [nonebot/adapter-red#22]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://chronocat.vercel.app) 并仍然认为这是一个Bug

# Bug

## 问题

bot.get_members返回空列表
已传入正确群号

## 使用环境:
- 操作系统 (Windows/Linux/Mac):
- Python 版本: 3.10.11
- Nonebot2 版本:2.1.0
- Chronocat 版本: 0.0.52
- Red 适配器版本:0.6.0

## 配置文件

```dotenv
```

**Comment by RF-Tar-Railt** [comment]
https://github.com/chrononeko/bugtracker/issues/20
这是chronocat的问题，与本适配器无关
