### ISSUE TITLE
[Feature]: 可以实现从群里面私聊用户的功能吗

### ISSUE THREAD

**Issue by mc23101** [nonebot/adapter-red#23]
### 确认项

- [X] 新特性的目的明确
- [X] 我已经使用过该项目并且了解其功能

### 希望能解决的问题

部分兑换码功能需要私聊发送，请问能否实现。

### 描述所需要的功能

从群里面私聊玩家，临时对话功能

**Comment by RF-Tar-Railt** [comment]
这与本适配器无关，你可以前往 https://github.com/chrononeko/bugtracker 提相关问题
