### ISSUE TITLE
[Feature]: 希望可以增加群成员减少的Event

### ISSUE THREAD

**Issue by qn8524king** [nonebot/adapter-red#24]
### 确认项

- [X] 新特性的目的明确
- [X] 我已经使用过该项目并且了解其功能

### 希望能解决的问题

有时候bot退群需要清理一些数据，以及别人退群之类的需要做一些记录，希望可以实装一下这个群成员减少逻辑~

### 描述所需要的功能

希望可以实装群成员减少的消息通知

**Comment by RF-Tar-Railt** [comment]
找 chronocat去
退群不会在群内显示消息，只通过消息没法检测是否有人退群
