### ISSUE TITLE
[Bug]: 发送tencent标准的silk语音时，好友私聊发送正常并可以播放，群组发送后PC端无法播放，手机端正常

### ISSUE THREAD

**Issue by qn8524king** [nonebot/adapter-red#26]
### 确认项

- [X] 问题的标题明确
- [X] 我翻阅过其他的 issue 并且找不到类似的问题
- [X] 我已经阅读了[相关文档](https://chronocat.vercel.app) 并仍然认为这是一个 Bug
- [X] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Windows

### Python 版本

3.8.16

### NoneBot 版本

2.1.1

### 适配器

0.6.0

### 协议端

0.0.52

### 描述问题

https://github.com/chrononeko/bugtracker/issues/49

发送语音时，通过编码器正常编码至silk格式后，发送至群组里会呈现出图片的样式（安卓QQ和NTQQ正常）

### 复现步骤

1.使用ffmpeg+编码器将wav编码转换至pcm再转换为silk
2.读取silk字节流并发送

### 期望的结果

可以正常发送语音

### 截图或日志

PCQQ:
![image](https://github.com/nonebot/adapter-red/assets/49012015/0bd9d087-e6a8-439f-be6a-73ada3714685)

**Comment by qn8524king** [comment]
根据chrononeko那面的说法，发送语音需要结尾命名.amr后缀

**Comment by ilharp** [comment]
具体需要修改的代码在这里：

https://github.com/nonebot/adapter-red/blob/69bb6fe70633538892f2ca898a863f6ab5e752bd/nonebot/adapters/red/message.py#L176

如果是语音的话，后面加一个 `.amr` 即可。
