### ISSUE TITLE
Error while process data from websocket

### ISSUE THREAD

**Issue by UKMeng** [nonebot/adapter-red#8]
## 环境

- nonebot 版本：2.1.0
- python版本：3.10.11
- adapter-red版本：0.3.0
- 驱动器：~httpx+~websockets
- Chronocat版本: 0.0.42
- 操作系统：macOS

## 问题

私聊或群聊一有消息就报日志中的错误，希望大佬们帮忙看一下，谢谢！

## 日志

```
09-18 12:39:49 [INFO] nonebot | red | Bot XXXX connected, Chronocat Version: 0.0.42
09-18 12:39:55 [ERROR] nonebot | red | Error while process data from websocket ws://localhost:16530/. Trying to reconnect...
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 118, in _forward_ws
    await self._loop(bot, ws)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 222, in _loop
    _handle_message(msg)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 168, in _handle_message
    _data = MessageModel.parse_obj(message)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 5 validation errors for Message
senderUid
  field required (type=value_error.missing)
avatarPendant
  field required (type=value_error.missing)
feedId
  field required (type=value_error.missing)
nameType
  field required (type=value_error.missing)
avatarFlag
  field required (type=value_error.missing)
```

**Comment by RF-Tar-Railt** [comment]
更新0.4.0试试

**Comment by UKMeng** [comment]
> 更新0.4.0试试

感谢回复，试了一下，群聊不报错了，私聊还有warning，报错日志如下

```
09-18 14:11:50 [WARNING] nonebot | RedProtocol | Failed to parse message data: {'msgId': '7280044773499471839', 'msgRandom': '1132562756', 'msgSeq': '266', 'cntSeq': '0', 'chatType': 1, 'msgType': 2, 'subMsgType': 1, 'sendType': 0, 'channelId': '', 'guildId': '', 'guildCode': '0', 'fromUid': '0', 'fromAppid': '0', 'msgTime': '1695017510', 'msgMeta': '0x', 'sendStatus': 2, 'sendMemberName': '', 'sendNickName': '', 'guildName': '', 'channelName': '', 'elements': [{'elementType': 1, 'elementId': '7280044773499471838', 'extBufForUI': '0x', 'textElement': {'content': '1', 'atType': 0, 'atUid': '0', 'atTinyId': '0', 'atNtUid': '', 'subElementType': 0, 'atChannelId': '0'}}], 'records': [], 'emojiLikesList': [], 'commentCnt': '0', 'directMsgFlag': 0, 'directMsgMembers': [], 'peerName': '', 'editable': False, 'avatarMeta': '', 'roleId': '0', 'timeStamp': '0', 'isImportMsg': False, 'atType': 0, 'roleType': 0, 'fromChannelRoleInfo': {'roleId': '0', 'name': '', 'color': 0}, 'fromGuildRoleInfo': {'roleId': '0', 'name': '', 'color': 0}, 'levelRoleInfo': {'roleId': '0', 'name': '', 'color': 0}, 'recallTime': '0', 'isOnlineMsg': True, 'generalFlags': '0x', 'clientSeq': '24653', 'senderUin': 'XXXXX', 'peerUin': 'XXXX'}
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 119, in _forward_ws
    await self._loop(bot, ws)
  File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 231, in _loop
    _handle_message(msg)
> File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 170, in _handle_message
    _data = MessageModel.parse_obj(message)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Message
peerUid
  field required (type=value_error.missing)
```

另外echo插件似乎不起效，我不确定是哪里的问题
```
09-18 14:10:27 [SUCCESS] nonebot | RedProtocol XXXXXX | [message.group]: Message from SUPERUSERS in UKM个人群: \echo test
09-18 14:10:27 [DEBUG] nonebot | Checking for matchers in priority 1...
09-18 14:10:27 [DEBUG] nonebot | Checking for matchers completed
```

**Comment by RF-Tar-Railt** [comment]
> > 更新0.4.0试试
> 
> 感谢回复，试了一下，群聊不报错了，私聊还有warning，报错日志如下
> 
> ```
> 09-18 14:11:50 [WARNING] nonebot | RedProtocol | Failed to parse message data: {'msgId': '7280044773499471839', 'msgRandom': '1132562756', 'msgSeq': '266', 'cntSeq': '0', 'chatType': 1, 'msgType': 2, 'subMsgType': 1, 'sendType': 0, 'channelId': '', 'guildId': '', 'guildCode': '0', 'fromUid': '0', 'fromAppid': '0', 'msgTime': '1695017510', 'msgMeta': '0x', 'sendStatus': 2, 'sendMemberName': '', 'sendNickName': '', 'guildName': '', 'channelName': '', 'elements': [{'elementType': 1, 'elementId': '7280044773499471838', 'extBufForUI': '0x', 'textElement': {'content': '1', 'atType': 0, 'atUid': '0', 'atTinyId': '0', 'atNtUid': '', 'subElementType': 0, 'atChannelId': '0'}}], 'records': [], 'emojiLikesList': [], 'commentCnt': '0', 'directMsgFlag': 0, 'directMsgMembers': [], 'peerName': '', 'editable': False, 'avatarMeta': '', 'roleId': '0', 'timeStamp': '0', 'isImportMsg': False, 'atType': 0, 'roleType': 0, 'fromChannelRoleInfo': {'roleId': '0', 'name': '', 'color': 0}, 'fromGuildRoleInfo': {'roleId': '0', 'name': '', 'color': 0}, 'levelRoleInfo': {'roleId': '0', 'name': '', 'color': 0}, 'recallTime': '0', 'isOnlineMsg': True, 'generalFlags': '0x', 'clientSeq': '24653', 'senderUin': 'XXXXX', 'peerUin': 'XXXX'}
> Traceback (most recent call last):
>   File "<string>", line 17, in <module>
>   File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
>     get_driver().run(*args, **kwargs)
>   File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 70, in run
>     loop.run_until_complete(self._serve())
>   File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
>     self.run_forever()
>   File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
>     self._run_once()
>   File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
>     handle._run()
>   File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 119, in _forward_ws
>     await self._loop(bot, ws)
>   File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 231, in _loop
>     _handle_message(msg)
> > File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 170, in _handle_message
>     _data = MessageModel.parse_obj(message)
>   File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
>     return cls(**obj)
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
>     raise validation_error
> pydantic.error_wrappers.ValidationError: 1 validation error for Message
> peerUid
>   field required (type=value_error.missing)
> ```
> 
> 另外echo插件似乎不起效，我不确定是哪里的问题
> 
> ```
> 09-18 14:10:27 [SUCCESS] nonebot | RedProtocol XXXXXX | [message.group]: Message from SUPERUSERS in UKM个人群: /echo test
> 09-18 14:10:27 [DEBUG] nonebot | Checking for matchers in priority 1...
> 09-18 14:10:27 [DEBUG] nonebot | Checking for matchers completed
> ```

0.4.1再试试

另外，echo插件的命令需要 `to_me`，也就是你得输入 `@机器人 /echo XXX`

**Comment by UKMeng** [comment]
> > > 更新0.4.0试试
> > 
> > 
> > 感谢回复，试了一下，群聊不报错了，私聊还有warning，报错日志如下
> > ```
> > 09-18 14:11:50 [WARNING] nonebot | RedProtocol | Failed to parse message data: {'msgId': '7280044773499471839', 'msgRandom': '1132562756', 'msgSeq': '266', 'cntSeq': '0', 'chatType': 1, 'msgType': 2, 'subMsgType': 1, 'sendType': 0, 'channelId': '', 'guildId': '', 'guildCode': '0', 'fromUid': '0', 'fromAppid': '0', 'msgTime': '1695017510', 'msgMeta': '0x', 'sendStatus': 2, 'sendMemberName': '', 'sendNickName': '', 'guildName': '', 'channelName': '', 'elements': [{'elementType': 1, 'elementId': '7280044773499471838', 'extBufForUI': '0x', 'textElement': {'content': '1', 'atType': 0, 'atUid': '0', 'atTinyId': '0', 'atNtUid': '', 'subElementType': 0, 'atChannelId': '0'}}], 'records': [], 'emojiLikesList': [], 'commentCnt': '0', 'directMsgFlag': 0, 'directMsgMembers': [], 'peerName': '', 'editable': False, 'avatarMeta': '', 'roleId': '0', 'timeStamp': '0', 'isImportMsg': False, 'atType': 0, 'roleType': 0, 'fromChannelRoleInfo': {'roleId': '0', 'name': '', 'color': 0}, 'fromGuildRoleInfo': {'roleId': '0', 'name': '', 'color': 0}, 'levelRoleInfo': {'roleId': '0', 'name': '', 'color': 0}, 'recallTime': '0', 'isOnlineMsg': True, 'generalFlags': '0x', 'clientSeq': '24653', 'senderUin': 'XXXXX', 'peerUin': 'XXXX'}
> > Traceback (most recent call last):
> >   File "<string>", line 17, in <module>
> >   File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
> >     get_driver().run(*args, **kwargs)
> >   File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 70, in run
> >     loop.run_until_complete(self._serve())
> >   File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
> >     self.run_forever()
> >   File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
> >     self._run_once()
> >   File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
> >     handle._run()
> >   File "/Users/ukm/.pyenv/versions/3.10.11/lib/python3.10/asyncio/events.py", line 80, in _run
> >     self._context.run(self._callback, *self._args)
> >   File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 119, in _forward_ws
> >     await self._loop(bot, ws)
> >   File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 231, in _loop
> >     _handle_message(msg)
> > > File "/Users/ukm/Developer/Python/NoneBot/red/.venv/lib/python3.10/site-packages/nonebot/adapters/red/adapter.py", line 170, in _handle_message
> >     _data = MessageModel.parse_obj(message)
> >   File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
> >     return cls(**obj)
> >   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> >     raise validation_error
> > pydantic.error_wrappers.ValidationError: 1 validation error for Message
> > peerUid
> >   field required (type=value_error.missing)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外echo插件似乎不起效，我不确定是哪里的问题
> > ```
> > 09-18 14:10:27 [SUCCESS] nonebot | RedProtocol XXXXXX | [message.group]: Message from SUPERUSERS in UKM个人群: /echo test
> > 09-18 14:10:27 [DEBUG] nonebot | Checking for matchers in priority 1...
> > 09-18 14:10:27 [DEBUG] nonebot | Checking for matchers completed
> > ```
> 
> 0.4.1再试试
> 
> 另外，echo插件的命令需要 `to_me`，也就是你得输入 `@机器人 /echo XXX`

都解决了，非常感谢您花时间解决和解答我的问题
